-- AlterTable
ALTER TABLE `Banner` ADD COLUMN `position` ENUM('HOME_MAIN_SLIDER', 'HOME_MIDDLE_BANNER', 'HOME_BOTTOM_BANNER', 'PRODUCT_SIDEBAR', 'CATEGORY_HEADER') NOT NULL DEFAULT 'HOME_MAIN_SLIDER';
